# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-11 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0002_auto_20200210_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gram.Comments'),
        ),
    ]
