# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-12 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200211_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='date_posted',
            new_name='dateposted',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='timestamp',
            new_name='dateposted',
        ),
    ]
